version: "3"

services:
  # backend:
  #   build: back
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./back:/back

  frontend:
    build: front
    command: npm run dev
    environment:
      - NODE_ENV=development
    ports:
      - 8080:8080
    volumes:
      - ./front:/front
      - /front/node_modules
    