version: "2"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DATABASE=animeaux_development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - ./apps/back/tmp/db:/var/lib/postgresql/data

  back:
    build: apps/back
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./apps/back:/back
      - ./apps/back/config/secrets.yml:/back/config/secrets.yml
    ports:
      - 3000:3000
    depends_on:
      - db

  front:
    build: apps/front
    command: npm run dev
    environment:
      - NODE_ENV=development
    ports:
      - 8080:8080
    volumes:
      - ./apps/front:/app
    